import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="h-[62px] w-full flex items-center">
          <div className="ml-5">
            <img src="/images/logo-pink.svg" alt="" />
          </div>
          <h1 className="mr-auto ml-2 text-2xl text-primary">Your Notes</h1>
          <div className="flex space-x-4 mr-6">
            <h1 className="font-poppins text-3xl text-primary font-bold">
              Ar
            </h1>
            <img src="/images/dark.svg" alt="" />
            <img src="/images/user.svg" alt="" />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
